export const products=[
    {
     "name": "WebCam",
     "colors": "Blue",
     "category": "Cam",
     "images": "https://static.bhphoto.com/images/multiple_images/images500x500/1348750124_IMG_273779.jpg",
     "brand": "Logitech",
     "stock": 1,
     "price": 41,
     "summary": "aliquam quis turpis eget elit sodales scelerisque mauris sit amet eros suspendisse accumsan tortor",
     "description": "maecenas pulvinar lobortis est phasellus sit amet erat nulla tempus vivamus in felis eu sapien cursus",
     "status":"New"
    },
    {
     "name": "Cabinet",
     "colors": "Fuscia",
     "category": "Replacement",
     "images": "https://www.hd-tecnologia.com/imagenes/articulos/2013/02/Thermaltake-Chaser-A31-Rosa.jpg",
     "brand": "Thermaltake ",
     "stock": 2,
     "price": 71,
     "summary": "sagittis nam congue risus semper porta volutpat quam pede lobortis ligula sit",
     "description": "elementum pellentesque quisque porta volutpat erat quisque erat eros viverra",
     "status":"New"
    },
    {
     "name": "Notebook",
     "colors": "Goldenrod",
     "category": "Computer",
     "images": "https://www.notebookcheck.org/fileadmin/Notebooks/Jumper/Tech_Ez_Book_X3_Air/Jumper_EZbook_X3_Air_5.jpg",
     "brand": "Jumper EZbook",
     "stock": 1,
     "price": 41,
     "summary": "lacus at velit vivamus vel nulla eget eros elementum pellentesque quisque porta volutpat erat quisque erat eros viverra",
     "description": "ligula in lacus curabitur at ipsum ac tellus semper interdum mauris ullamcorper purus sit",
     "status":"Used"
    },
    {
     "name": "M2",
     "colors": "Blue",
     "category": "Cam",
     "images": "https://s3-sa-east-1.amazonaws.com/saasargentina/vSjGzHuGDHIcxWziCUWH/imagen",
     "brand": "Western digital",
     "stock": 5,
     "price": 46,
     "summary": "sed ante vivamus tortor duis mattis egestas metus aenean fermentum donec ut mauris",
     "description": "ipsum integer a nibh in quis justo maecenas rhoncus aliquam lacus morbi quis tortor id nulla ultrices",
     "status":"New"
    },
    {
     "name": "WebCam",
     "colors": "Red",
     "category": "Cam",
     "images": "https://img.tttcdn.com/product/xy/2000/2000/p/gu1/C/R/C9469B-R/C9469B-R-1-1f83-PVte.jpg",
     "brand": "LG",
     "stock": 1,
     "price": 7,
     "summary": "vitae ipsum aliquam non mauris morbi non lectus aliquam sit amet",
     "description": "in felis donec semper sapien a libero nam dui proin leo odio porttitor id consequat in",
     "status":"Used"
    },
    {
     "name": "Speakers",
     "colors": ["Blue","Black"],
     "category": "Audio",
     "images": "https://mauricomputacion.com.ar/images/productos/500x500/21817.webp",
     "brand": "Genius",
     "stock": 7,
     "price": 54,
     "summary": "turpis sed ante vivamus tortor duis mattis egestas metus aenean fermentum donec ut mauris eget massa tempor",
     "description": "blandit lacinia erat vestibulum sed magna at nunc commodo placerat praesent blandit nam nulla integer pede justo lacinia eget",
     "status":"New"
    },
    {
     "name": "Motherboard",
     "colors": "Blue",
     "category": "Component",
     "images": "https://upload.wikimedia.org/wikipedia/commons/6/6f/Apple-MacBook-2007-Motherboard.jpg",
     "brand": "Apple",
     "stock": 13,
     "price": 4,
     "summary": "eget elit sodales scelerisque mauris sit amet eros suspendisse accumsan tortor quis",
     "description": "ultrices vel augue vestibulum ante ipsum primis in faucibus orci luctus",
     "status":"New"
    },
    {
     "name": "Headphones",
     "colors": "Red",
     "category": "Audio",
     "images": "https://www.beatsbydre.com/content/dam/beats/web/product/headphones/solo3-wireless/pdp/solo3-pdp-p02.png.large.2x.png",
     "brand": "Wireless",
     "stock": 14,
     "price": 68,
     "summary": "odio porttitor id consequat in consequat ut nulla sed accumsan felis ut at dolor quis odio consequat varius integer ac",
     "description": "integer tincidunt ante vel ipsum praesent blandit lacinia erat vestibulum sed magna at nunc commodo placerat praesent blandit nam",
     "status":"New"
    },
    {
     "name": "RAM",
     "colors": "Green",
     "category": "Component",
     "images": "https://s3-sa-east-1.amazonaws.com/saasargentina/TNsYjD2GXXnaxHp96erf/imagen",
     "brand": "Generic",
     "stock": 15,
     "price": 29,
     "summary": "ut erat curabitur gravida nisi at nibh in hac habitasse platea dictumst aliquam augue",
     "description": "feugiat non pretium quis lectus suspendisse potenti in eleifend quam a odio in hac habitasse platea",
     "status":"New"
    },
    {
     "name": "Keyboard",
     "colors": "Black",
     "category": "Peripheral",
     "images": "https://resource.logitechg.com/w_692,c_limit,q_auto,f_auto,dpr_1.0/d_transparent.gif/content/dam/gaming/en/non-braid/g213-finch/g213-gallery-1-nb.png?v=1",
     "brand": "gAMING",
     "stock": 1,
     "price": 98,
     "summary": "morbi ut odio cras mi pede malesuada in imperdiet et commodo vulputate justo in blandit",
     "description": "vulputate luctus cum sociis natoque penatibus et magnis dis parturient montes nascetur ridiculus mus vivamus vestibulum sagittis sapien cum sociis",
     "status":"Used"
    },
    {
     "name": "Mouse",
     "colors": ["Blue","Turquoise"],
     "category": "Peripheral",
     "images": "https://logitechar.vteximg.com.br/arquivos/ids/157535-1000-1000/910-005795_3.png?v=637345251328370000",
     "brand": "Gaming",
     "stock": 17,
     "price": 42,
     "summary": "justo morbi ut odio cras mi pede malesuada in imperdiet et commodo vulputate justo in blandit ultrices enim lorem",
     "description": "dignissim vestibulum vestibulum ante ipsum primis in faucibus orci luctus et ultrices",
     "status":"New"
    },
    {
     "name": "CPU",
     "colors": ["Gray","Green"],
     "category": "Component",
     "images": "https://www.profesionalreview.com/wp-content/uploads/2018/05/Intel-Pentium-Silver-J5005-alcanza-el-rendimiento-del-Core-2-Quad-Q6600-2-.jpg",
     "brand": "Intel",
     "stock": 18,
     "price": 71,
     "summary": "in consequat ut nulla sed accumsan felis ut at dolor quis",
     "description": "curae mauris viverra diam vitae quam suspendisse potenti nullam porttitor lacus at turpis donec posuere metus vitae ipsum aliquam",
     "status":"New"
    },
    {
     "name": "Display",
     "colors": "Black",
     "category": "Component",
     "images": "https://apollo-virginia.akamaized.net/v1/files/oka2bjsha5sw1-AR/image;s=360x0",
     "brand": "Samsung",
     "stock": 1,
     "price": 21,
     "summary": "aliquet pulvinar sed nisl nunc rhoncus dui vel sem sed sagittis nam congue risus semper porta",
     "description": "vel enim sit amet nunc viverra dapibus nulla suscipit ligula in lacus curabitur at ipsum ac tellus semper interdum",
     "status":"Used"
    },
    {
     "name": "PC",
     "colors": "White",
     "category": "Comuter",
     "images": "https://album.mediaset.es/eimg/2020/07/10/NUoYRS2t7d6OSh9gszeYk6.jpg",
     "brand": "Microsoft",
     "stock": 20,
     "price": 59,
     "summary": "nibh quisque id justo sit amet sapien dignissim vestibulum vestibulum ante",
     "description": "nulla suspendisse potenti cras in purus eu magna vulputate luctus cum sociis natoque penatibus et magnis dis",
     "status":"New"
    },
    {
     "name": "Microphone",
     "colors": ["Black","Red"],
     "category": "Peripheral",
     "images": "https://http2.mlstatic.com/D_NQ_NP_963302-MLA32166263812_092019-O.webp",
     "brand": "Hyper",
     "stock": 1,
     "price": 83,
     "summary": "donec ut mauris eget massa tempor convallis nulla neque libero convallis eget",
     "description": "venenatis tristique fusce congue diam id ornare imperdiet sapien urna pretium nisl ut volutpat sapien",
     "status":"Used"
    },
    {
     "name": "Macbook",
     "colors": "Orange",
     "category": "PC",
     "images": "https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcRsT2pgFedeLts8jZrng32lw3bKXeUD72oyAVxWoct0s7IDdSofH5whYxedUxzFmHLSelY&usqp=CAU",
     "brand": "Apple",
     "stock": 22,
     "price": 100,
     "summary": "sapien quis libero nullam sit amet turpis elementum ligula vehicula consequat",
     "description": "eu felis fusce posuere felis sed lacus morbi sem mauris laoreet ut rhoncus aliquet pulvinar sed nisl",
     "status":"New"
    },
    {
     "name": "SSD",
     "colors": "Gray",
     "category": "Disc",
     "images": "https://techbuysv.com/wp-content/uploads/2016/03/ktc-product-ssd-a400-sa400s37-240gb-3-zm-lg-1.jpg",
     "brand": "kingston",
     "stock": 23,
     "price": 4,
     "summary": "id mauris vulputate elementum nullam varius nulla facilisi cras non velit nec nisi vulputate nonummy maecenas tincidunt lacus",
     "description": "tortor sollicitudin mi sit amet lobortis sapien sapien non mi integer ac neque",
     "status":"New"
    },
    {
     "name": "HDD",
     "colors": "Black",
     "category": "Component",
     "images": "https://www.profesionalreview.com/wp-content/uploads/2019/10/Disco-duro.jpg",
     "brand": "Exos",
     "stock": 24,
     "price": 86,
     "summary": "sodales sed tincidunt eu felis fusce posuere felis sed lacus morbi sem mauris laoreet ut rhoncus aliquet pulvinar",
     "description": "in faucibus orci luctus et ultrices posuere cubilia curae mauris viverra diam vitae quam",
     "status":"New"
    },
    {
     "name": "Video card",
     "colors": "Blue",
     "category": "Component",
     "images": "https://http2.mlstatic.com/D_NQ_NP_834093-MLA49727562476_042022-O.webp",
     "brand": "Hellhound ",
     "stock": 25,
     "price": 99,
     "summary": "elit proin interdum mauris non ligula pellentesque ultrices phasellus id",
     "description": "et magnis dis parturient montes nascetur ridiculus mus etiam vel augue vestibulum rutrum rutrum neque aenean auctor gravida sem praesent",
     "status":"New"
    },
    {
     "name": "Cooler Disipador Amd Original Socket Am4 ",
     "colors": "Black",
     "category": "Cooler",
     "images": "https://mauricomputacion.com.ar/images/productos/500x500/23097.webp",
     "brand": "Amd",
     "stock": 1,
     "price": 70,
     "summary": "leo rhoncus sed vestibulum sit amet cursus id turpis integer aliquet massa id lobortis convallis tortor risus dapibus",
     "description": "non mattis pulvinar nulla pede ullamcorper augue a suscipit nulla elit ac nulla sed vel enim sit amet nunc",
     "status":"Used"
    },
    {
     "name": "PC Pentium",
     "colors": "Black",
     "category": "Computer",
     "images": "https://http2.mlstatic.com/D_NQ_NP_809307-MLA51341944767_082022-O.webp",
     "brand": "Dell",
     "stock": 1,
     "price": 17,
     "summary": "viverra diam vitae quam suspendisse potenti nullam porttitor lacus at turpis donec posuere metus",
     "description": "in magna bibendum imperdiet nullam orci pede venenatis non sodales sed tincidunt eu felis fusce",
     "status":"Used"
    },
    {
     "name": "Mini Wireless N USB Adapter",
     "colors": "Black",
     "category": "Antenna",
     "images": "https://http2.mlstatic.com/D_NQ_NP_884444-MLA46603451558_072021-O.webp",
     "brand": "Apple",
     "stock": 28,
     "price": 88,
     "summary": "pellentesque at nulla suspendisse potenti cras in purus eu magna vulputate luctus cum sociis natoque penatibus et magnis dis parturient",
     "description": "amet erat nulla tempus vivamus in felis eu sapien cursus",
     "status":"New"
    },
    {
     "name": "Pendrive",
     "colors": ["Black","Red"],
     "category": "Disk",
     "images": "https://http2.mlstatic.com/D_NQ_NP_834922-MLA32121762817_092019-O.webp",
     "brand": "SanDisk ",
     "stock": 5,
     "price": 78,
     "summary": "adipiscing elit proin interdum mauris non ligula pellentesque ultrices phasellus id sapien in sapien iaculis congue vivamus metus arcu",
     "description": "vestibulum quam sapien varius ut blandit non interdum in ante vestibulum ante ipsum primis",
     "status":"New"
    },
    {
     "name": "External hard drive",
     "colors": "Black",
     "category": "Disk",
     "images": "https://http2.mlstatic.com/D_NQ_NP_997406-MLA48157646660_112021-O.webp",
     "brand": "Seagate",
     "stock": 30,
     "price": 50,
     "summary": "luctus tincidunt nulla mollis molestie lorem quisque ut erat curabitur gravida nisi at nibh in hac habitasse platea dictumst aliquam",
     "description": "risus praesent lectus vestibulum quam sapien varius ut blandit non interdum in ante vestibulum ante ipsum",
     "status":"New"
    },
    {
     "name": "Neetbook",
     "colors": "White",
     "category": "Computer",
     "images": "https://media.ambito.com/p/2883f6860ed7a1b37eebf0b16e9cf461/adjuntos/239/imagenes/039/584/0039584693/730x0/smart/conectar-igualdadjpg.jpg",
     "brand": "EDUNEC",
     "stock": 1,
     "price": 38,
     "summary": "dictumst etiam faucibus cursus urna ut tellus nulla ut erat id mauris",
     "description": "eu tincidunt in leo maecenas pulvinar lobortis est phasellus sit amet erat nulla tempus vivamus in felis eu",
     "status":"Used"
    },
    {
     "name": "PSU ",
     "colors": "Black",
     "category": "Component",
     "images": "https://www.corsair.com/medias/sys_master/images/images/h0d/h50/9112047452190/-CP-9020179-NA-Gallery-RM750x-PSU-01.png",
     "brand": "Corsair",
     "stock": 32,
     "price": 32,
     "summary": "integer pede justo lacinia eget tincidunt eget tempus vel pede morbi porttitor lorem id ligula suspendisse",
     "description": "sed ante vivamus tortor duis mattis egestas metus aenean fermentum donec ut mauris eget massa",
     "status":"New"
    },
    {
     "name": "Video card",
     "colors": ["Red","Black"],
     "category": "Component",
     "images": "https://http2.mlstatic.com/D_NQ_NP_840841-MLA46165183395_052021-O.webp",
     "brand": "Gaming",
     "stock": 1,
     "price": 72,
     "summary": "et commodo vulputate justo in blandit ultrices enim lorem ipsum dolor sit amet consectetuer adipiscing elit proin interdum mauris non",
     "description": "vel lectus in quam fringilla rhoncus mauris enim leo rhoncus sed vestibulum",
     "status":"Used"
    },
    {
     "name": "MSI GEFORCE RTX 3060 TI GAMING X 8G LHR",
     "colors": ["Black", "White"],
     "category": "Graphics",
     "images": "https://clonesyperifericos.com/wp-content/uploads/2022/09/1-10-600x600.jpg",
     "brand": "MSI",
     "stock": 5,
     "price": 519,
     "summary": "Es hora de ponerse los colores del equipo. Sincroniza la iluminación con otros dispositivos compatibles para llevar el espectáculo de luces a otro nivel.",
     "description": "El trazado de rayos es el santo grial de los gráficos de los videojuegos, simula el comportamiento físico de la luz para ofrecer una representación de calidad cinematográfica en tiempo real incluso en los juegos más exigentes a nivel visual.",
     "status": "New"
    },
    {
        "name": "Gamer Chair DXRACER FORMULA P09 BLACK",
        "colors": ["Black", "Red", "White"],
        "category": "Component",
        "images": "https://clonesyperifericos.com/wp-content/uploads/2022/09/1-7-600x600.jpg",
        "brand": "Dx Racer",
        "stock": 7,
        "price": 349,
        "summary": "Ya sea que esté jugando, trabajando o tomando una siesta, nuestra silla brinda un soporte de ángulo perfecto de 90° a 135° para satisfacer todas sus necesidades.",
        "description": "Construida con el cuero preferido por los asientos de carreras junto con un diseño de combinación de colores y costuras detalladas, nuestra serie Prince puede combinar perfectamente con el estilo de su configuración y ayudarlo a dominar el mundo de los juegos.",
        "status": "New"
       },
       {
        "name": "MONITOR SAMSUNG ODYSSEY G4 27 IPS 240HZ",
        "colors": ["Black"],
        "category": "Graphics",
        "images": "https://clonesyperifericos.com/wp-content/uploads/2022/08/1-76-600x600.jpg",
        "brand": "Samsung",
        "stock": 25,
        "price": 409,
        "summary": "Escenas a toda velocidad. La tasa de refresco de 240Hz elimina el retardo para ofrecerte un juego estimulante.",
        "description": "Una forma realista de desafiar la reaIidad, en la que experimentarás tus juegos como nunca antes. El panel IPS te permite experimentar los colores con nitidez y con un amplio ángulo de visión de 178º, para una mayor claridad desde cualquier punto de vista. Disfruta de más píxeles y una mayor profundidad, para que tus juegos se acerquen más que nunca a la realidad",
        "status": "New"
       },
       {
        "name": "FUENTE DE PODER CORSAIR FULL MODULAR RM 1000W GOLD",
        "colors": ["Black"],
        "category": "Component",
        "images": "https://clonesyperifericos.com/wp-content/uploads/2022/08/1-75-600x600.jpg",
        "brand": "Corsair",
        "stock": 17,
        "price": 219,
        "summary": "EFICIENCIA CON CERTIFICACIÓN GOLD CON REGULACIÓN DEL VOLTAJE EXTREMADAMENTE PRECISA PARA OFRECER UN RENDIMIENTO SUPERIOR.",
        "description": "Las fuentes alimentación RMx Series ofrecen un control del voltaje extremadamente preciso, un funcionamiento silencioso, una eficiencia con certificación Gold y un conjunto de cables totalmente modulares.",
        "status": "New"
       },
       {
        "name": "BOARD GIGABYTE B660M GAMING X AX DDR4",
        "colors": ["Black"],
        "category": "Component",
        "images": "https://clonesyperifericos.com/wp-content/uploads/2022/08/1-72-600x600.jpg",
        "brand": "Gigabyte",
        "stock": 4,
        "price": 199,
        "summary": "La entrega de energía más limpia y eficiente a la CPU con un mejor rendimiento térmico garantiza la estabilidad bajo altas frecuencias de CPU y cargas pesadas. DrMOS de 8+1+1 fases*",
        "description": "Las placas base GIGABYTE B660 están listas para funcionar con los dispositivos PCIe 4.0 que se espera que experimenten el doble de ancho de banda que los dispositivos PCIe 3.0 actuales.",
        "status": "New"
       },
       {
        "name": "KIT 3 VENTILADORES THERMALTAKE PURE 12 LED ROJO",
        "colors": ["White"],
        "category": "Peripheral",
        "images": "https://clonesyperifericos.com/wp-content/uploads/2022/08/3-62-600x600.jpg",
        "brand": "Thermaltake",
        "stock": 3,
        "price": 29,
        "summary": "El ventilador de 12 LED puro está diseñado para enfriarse en silencio, por lo que el usuario puede mantener su mente centrada en la tarea a mano sin molestarse.",
        "description": "El ventilador Thermaltake Pure 12 LED viene con un rendimiento confiable y estable y un estilo magnífico y vibrante. Disponible en 120 mm, el ventilador Pure 12 LED ofrece el equilibrio perfecto entre silencio, estilo y eficiencia.",
        "status": "New"
       },
       {
        "name": "SSD ADATA ULTIMATE SU650 512GB 2.5",
        "colors": ["Black"],
        "category": "Component",
        "images": "https://clonesyperifericos.com/wp-content/uploads/2022/09/1-1-600x600.jpg",
        "brand": "Adata",
        "stock": 9,
        "price": 19,
        "summary": "La unidad de estado sólido Ultimate SU650 implementa Flash NAND 3D y un controlador de alta velocidad, ofreciendo capacidades de hasta 960 GB.",
        "description": "Ofrece un rendimiento de lectura/escritura de hasta 520/450MB/s y mayor fiabilidad que los SSD con NAND 2D. El SU650 cuenta con caché SLC y tecnologías avanzadas de corrección de errores para garantizar un rendimiento e integridad de datos optimizados. Para aquellos que quieren experimentar una mejora clara de su PC, el SU650 definitivamente es una excelente opción con una gran relación costo-rendimiento.",
        "status": "New"
       },
       {
        "name": "PARLANTES LOGITECH Z407 2.0 BLUETOOTH",
        "colors": ["Black"],
        "category": "Peripheral",
        "images": "https://clonesyperifericos.com/wp-content/uploads/2022/08/10-5-600x600.jpg",
        "stock": 24,
        "price": 99,
        "summary": "80 vatios de potencia y procesamiento de señales digitales (DSP) preciso para disfrutar de un sonido vibrante, envolvente.",
        "description": "SONIDO INMERSIVO – El sistema de altavoces 2.1 sintonizado por expertos ofrece 80 vatios de potencia de pico y 40 vatios reales. El procesamiento de señal digital ofrece un perfil de sonido equilibrado y graves mejorados, para un sonido envolvente y genuino, desde agudos nítidos a sonidos medios y bajos potentes, sin comprometer la plenitud de los graves profundos.",
        "status": "New"
       },
       {
        "name": "DIADEMA ASTRO A10 GEN 2 MULTIPLATAFORMA WHITE",
        "colors": ["White"],
        "category": "Peripheral",
        "images": "https://clonesyperifericos.com/wp-content/uploads/2022/08/0-9-600x600.jpg",
        "brand": "Astro",
        "stock": 10,
        "price": 74,
        "summary": "Calidad de sonido mejorada: los auriculares ASTRO Gaming A10 Gen 2 para PlayStation 5, PlayStation 4, Nintendo Switch, PC, Mac cuentan con controladores dinámicos de 1.260 in personalizados para que siempre puedas escuchar a tus juegos y compañeros de equipo con claridad y precisión",
        "description": "Mejora tu equipo para juego diario con los audífono con micrófono ASTRO A10 de segunda generación para PC/MAC, PS5, XBOX SERIES X|S, SWITCH, MOBILE. Considéralos como la siguiente evolución del equipo para PC que ya utilizas a diario. Audio formidable a través de transductores dinámicos de 32 mm, micrófono de varilla volteable para silenciar y construcción resistente con almohadillas de copas y de diadema reemplazables se combinan para ofrecer una experiencia sonora memorable. No hay que preocuparse por los sonidos oclusivos ni por comprar otros audífonos cuando las cosas empiezan a deteriorarse un poco.",
        "status": "New"
       },
       {
        "name": "",
        "colors": ["", ""],
        "category": "",
        "images": "",
        "stock": 1,
        "price": 20,
        "summary": "",
        "description": "",
        "status": ""
       },
       {
        "name": "",
        "colors": ["", ""],
        "category": "",
        "images": "",
        "stock": 1,
        "price": 20,
        "summary": "",
        "description": "",
        "status": ""
       },
       {
        "name": "",
        "colors": ["", ""],
        "category": "",
        "images": "",
        "stock": 1,
        "price": 20,
        "summary": "",
        "description": "",
        "status": ""
       },
       {
        "name": "",
        "colors": ["", ""],
        "category": "",
        "images": "",
        "stock": 1,
        "price": 20,
        "summary": "",
        "description": "",
        "status": ""
       },
       {
        "name": "",
        "colors": ["", ""],
        "category": "",
        "images": "",
        "stock": 1,
        "price": 20,
        "summary": "",
        "description": "",
        "status": ""
       },
       {
        "name": "",
        "colors": ["", ""],
        "category": "",
        "images": "",
        "stock": 1,
        "price": 20,
        "summary": "",
        "description": "",
        "status": ""
       },
       {
        "name": "",
        "colors": ["", ""],
        "category": "",
        "images": "",
        "stock": 1,
        "price": 20,
        "summary": "",
        "description": "",
        "status": ""
       },
       {
        "name": "",
        "colors": ["", ""],
        "category": "",
        "images": "",
        "stock": 1,
        "price": 20,
        "summary": "",
        "description": "",
        "status": ""
       },
       {
        "name": "",
        "colors": ["", ""],
        "category": "",
        "images": "",
        "stock": 1,
        "price": 20,
        "summary": "",
        "description": "",
        "status": ""
       },
       {
        "name": "",
        "colors": ["", ""],
        "category": "",
        "images": "",
        "stock": 1,
        "price": 20,
        "summary": "",
        "description": "",
        "status": ""
       },
       {
        "name": "",
        "colors": ["", ""],
        "category": "",
        "images": "",
        "stock": 1,
        "price": 20,
        "summary": "",
        "description": "",
        "status": ""
       },
       {
        "name": "",
        "colors": ["", ""],
        "category": "",
        "images": "",
        "stock": 1,
        "price": 20,
        "summary": "",
        "description": "",
        "status": ""
       },
       {
        "name": "",
        "colors": ["", ""],
        "category": "",
        "images": "",
        "stock": 1,
        "price": 20,
        "summary": "",
        "description": "",
        "status": ""
       },
       {
        "name": "",
        "colors": ["", ""],
        "category": "",
        "images": "",
        "stock": 1,
        "price": 20,
        "summary": "",
        "description": "",
        "status": ""
       },
       {
        "name": "",
        "colors": ["", ""],
        "category": "",
        "images": "",
        "stock": 1,
        "price": 20,
        "summary": "",
        "description": "",
        "status": ""
       },
       {
        "name": "",
        "colors": ["", ""],
        "category": "",
        "images": "",
        "stock": 1,
        "price": 20,
        "summary": "",
        "description": "",
        "status": ""
       },
       {
        "name": "",
        "colors": ["", ""],
        "category": "",
        "images": "",
        "stock": 1,
        "price": 20,
        "summary": "",
        "description": "",
        "status": ""
       },
       {
        "name": "",
        "colors": ["", ""],
        "category": "",
        "images": "",
        "stock": 1,
        "price": 20,
        "summary": "",
        "description": "",
        "status": ""
       },
]
export const categories=[
    {
        name:"Peripheral"
    },
    {
        name:"Replacement"
    },
    {
        name:"Component"
    },
    {
        name:"Memory"
    },
    {
        name:"Graphics"
    },
    {
        name:"Cooler"
    },
    {
        name:"Cam"
    }
]
