const data = [
    {
     "name": "Pass",
     "colors": "Khaki",
     "category": "n\/a",
     "images": "http:\/\/dummyimage.com\/245x100.png\/cc0000\/ffffff",
     "brand": "WisdomTree Emerging Markets Corporate Bond Fund",
     "stock": 1,
     "price": 17,
     "summary": "in felis donec semper sapien a libero nam dui proin leo odio porttitor id consequat in consequat ut nulla",
     "description": "lectus suspendisse potenti in eleifend quam a odio in hac habitasse platea dictumst maecenas"
    },
    {
     "name": "Drive",
     "colors": "Pink",
     "category": "Health Care",
     "images": "http:\/\/dummyimage.com\/113x100.png\/5fa2dd\/ffffff",
     "brand": "BiondVax Pharmaceuticals Ltd.",
     "stock": 2,
     "price": 28,
     "summary": "risus praesent lectus vestibulum quam sapien varius ut blandit non interdum in ante vestibulum ante ipsum primis",
     "description": "hac habitasse platea dictumst etiam faucibus cursus urna ut tellus nulla"
    },
    {
     "name": "Park",
     "colors": "Orange",
     "category": "Technology",
     "images": "http:\/\/dummyimage.com\/124x100.png\/ff4444\/ffffff",
     "brand": "Sohu.com Inc.",
     "stock": 3,
     "price": 83,
     "summary": "nec condimentum neque sapien placerat ante nulla justo aliquam quis turpis",
     "description": "posuere cubilia curae donec pharetra magna vestibulum aliquet ultrices erat tortor sollicitudin mi sit amet lobortis sapien sapien non"
    },
    {
     "name": "Drive",
     "colors": "Khaki",
     "category": "Capital Goods",
     "images": "http:\/\/dummyimage.com\/112x100.png\/5fa2dd\/ffffff",
     "brand": "Nortech Systems Incorporated",
     "stock": 4,
     "price": 12,
     "summary": "imperdiet sapien urna pretium nisl ut volutpat sapien arcu sed augue aliquam erat volutpat in",
     "description": "amet sapien dignissim vestibulum vestibulum ante ipsum primis in faucibus orci luctus"
    },
    {
     "name": "Junction",
     "colors": "Pink",
     "category": "Consumer Services",
     "images": "http:\/\/dummyimage.com\/177x100.png\/cc0000\/ffffff",
     "brand": "Cinemark Holdings Inc",
     "stock": 5,
     "price": 72,
     "summary": "in faucibus orci luctus et ultrices posuere cubilia curae donec pharetra magna vestibulum aliquet ultrices erat tortor sollicitudin mi sit",
     "description": "eget tincidunt eget tempus vel pede morbi porttitor lorem id ligula suspendisse"
    },
    {
     "name": "Parkway",
     "colors": "Fuscia",
     "category": "Consumer Services",
     "images": "http:\/\/dummyimage.com\/126x100.png\/ff4444\/ffffff",
     "brand": "Grupo Televisa S.A.",
     "stock": 6,
     "price": 58,
     "summary": "pretium iaculis justo in hac habitasse platea dictumst etiam faucibus cursus urna ut",
     "description": "ut blandit non interdum in ante vestibulum ante ipsum primis in faucibus orci luctus et ultrices"
    },
    {
     "name": "Street",
     "colors": "Mauv",
     "category": "Consumer Services",
     "images": "http:\/\/dummyimage.com\/211x100.png\/5fa2dd\/ffffff",
     "brand": "Gray Television, Inc.",
     "stock": 7,
     "price": 98,
     "summary": "in porttitor pede justo eu massa donec dapibus duis at velit",
     "description": "elementum nullam varius nulla facilisi cras non velit nec nisi vulputate nonummy maecenas"
    },
    {
     "name": "Lane",
     "colors": "Crimson",
     "category": "Health Care",
     "images": "http:\/\/dummyimage.com\/127x100.png\/cc0000\/ffffff",
     "brand": "OncoSec Medical Incorporated",
     "stock": 8,
     "price": 78,
     "summary": "mi nulla ac enim in tempor turpis nec euismod scelerisque quam",
     "description": "sapien urna pretium nisl ut volutpat sapien arcu sed augue aliquam"
    },
    {
     "name": "Parkway",
     "colors": "Khaki",
     "category": "n\/a",
     "images": "http:\/\/dummyimage.com\/193x100.png\/cc0000\/ffffff",
     "brand": "Wells Fargo &amp; Company",
     "stock": 9,
     "price": 82,
     "summary": "ut erat curabitur gravida nisi at nibh in hac habitasse platea dictumst aliquam augue quam sollicitudin vitae consectetuer",
     "description": "vestibulum quam sapien varius ut blandit non interdum in ante vestibulum ante ipsum primis in"
    },
    {
     "name": "Way",
     "colors": "Puce",
     "category": "Health Care",
     "images": "http:\/\/dummyimage.com\/106x100.png\/ff4444\/ffffff",
     "brand": "Lakeland Industries, Inc.",
     "stock": 10,
     "price": 63,
     "summary": "pede posuere nonummy integer non velit donec diam neque vestibulum eget vulputate ut",
     "description": "sollicitudin mi sit amet lobortis sapien sapien non mi integer ac neque duis bibendum morbi non quam nec dui"
    },
    {
     "name": "Lane",
     "colors": "Violet",
     "category": "Basic Industries",
     "images": "http:\/\/dummyimage.com\/177x100.png\/cc0000\/ffffff",
     "brand": "Fortune Brands Home &amp; Security, Inc.",
     "stock": 11,
     "price": 83,
     "summary": "elit proin interdum mauris non ligula pellentesque ultrices phasellus id sapien in sapien iaculis congue vivamus metus arcu adipiscing molestie",
     "description": "ultrices mattis odio donec vitae nisi nam ultrices libero non mattis pulvinar nulla pede ullamcorper augue"
    },
    {
     "name": "Trail",
     "colors": "Orange",
     "category": "Basic Industries",
     "images": "http:\/\/dummyimage.com\/184x100.png\/ff4444\/ffffff",
     "brand": "Sterling Construction Company Inc",
     "stock": 12,
     "price": 34,
     "summary": "in congue etiam justo etiam pretium iaculis justo in hac habitasse platea dictumst etiam",
     "description": "integer pede justo lacinia eget tincidunt eget tempus vel pede morbi porttitor"
    },
    {
     "name": "Parkway",
     "colors": "Goldenrod",
     "category": "n\/a",
     "images": "http:\/\/dummyimage.com\/155x100.png\/cc0000\/ffffff",
     "brand": "Gabelli Convertible and Income Securities Fund, Inc. (The)",
     "stock": 13,
     "price": 39,
     "summary": "bibendum imperdiet nullam orci pede venenatis non sodales sed tincidunt eu felis fusce posuere felis",
     "description": "ultrices phasellus id sapien in sapien iaculis congue vivamus metus arcu adipiscing molestie hendrerit at vulputate vitae nisl"
    },
    {
     "name": "Crossing",
     "colors": "Maroon",
     "category": "n\/a",
     "images": "http:\/\/dummyimage.com\/222x100.png\/dddddd\/000000",
     "brand": "M&amp;T Bank Corporation",
     "stock": 14,
     "price": 51,
     "summary": "maecenas tristique est et tempus semper est quam pharetra magna ac",
     "description": "eu massa donec dapibus duis at velit eu est congue elementum in hac habitasse platea dictumst"
    },
    {
     "name": "Road",
     "colors": "Indigo",
     "category": "Consumer Services",
     "images": "http:\/\/dummyimage.com\/213x100.png\/dddddd\/000000",
     "brand": "AMREP Corporation",
     "stock": 15,
     "price": 41,
     "summary": "justo etiam pretium iaculis justo in hac habitasse platea dictumst etiam faucibus cursus urna ut tellus",
     "description": "posuere cubilia curae donec pharetra magna vestibulum aliquet ultrices erat"
    },
    {
     "name": "Trail",
     "colors": "Green",
     "category": "Health Care",
     "images": "http:\/\/dummyimage.com\/133x100.png\/dddddd\/000000",
     "brand": "Novan, Inc.",
     "stock": 16,
     "price": 69,
     "summary": "eget tincidunt eget tempus vel pede morbi porttitor lorem id ligula suspendisse",
     "description": "fringilla rhoncus mauris enim leo rhoncus sed vestibulum sit amet"
    },
    {
     "name": "Trail",
     "colors": "Khaki",
     "category": "Technology",
     "images": "http:\/\/dummyimage.com\/216x100.png\/5fa2dd\/ffffff",
     "brand": "Inovalon Holdings, Inc.",
     "stock": 17,
     "price": 64,
     "summary": "in quis justo maecenas rhoncus aliquam lacus morbi quis tortor id",
     "description": "enim blandit mi in porttitor pede justo eu massa donec"
    },
    {
     "name": "Street",
     "colors": "Turquoise",
     "category": "Public Utilities",
     "images": "http:\/\/dummyimage.com\/188x100.png\/cc0000\/ffffff",
     "brand": "Shenandoah Telecommunications Co",
     "stock": 18,
     "price": 47,
     "summary": "donec odio justo sollicitudin ut suscipit a feugiat et eros vestibulum ac est lacinia nisi",
     "description": "orci vehicula condimentum curabitur in libero ut massa volutpat convallis morbi odio odio elementum eu"
    },
    {
     "name": "Park",
     "colors": "Blue",
     "category": "Capital Goods",
     "images": "http:\/\/dummyimage.com\/106x100.png\/dddddd\/000000",
     "brand": "The ExOne Company",
     "stock": 19,
     "price": 86,
     "summary": "eget eleifend luctus ultricies eu nibh quisque id justo sit amet sapien dignissim vestibulum vestibulum ante ipsum primis in",
     "description": "augue quam sollicitudin vitae consectetuer eget rutrum at lorem integer tincidunt ante"
    },
    {
     "name": "Circle",
     "colors": "Aquamarine",
     "category": "n\/a",
     "images": "http:\/\/dummyimage.com\/150x100.png\/ff4444\/ffffff",
     "brand": "Gabelli Dividend",
     "stock": 20,
     "price": 78,
     "summary": "amet lobortis sapien sapien non mi integer ac neque duis bibendum",
     "description": "integer ac neque duis bibendum morbi non quam nec dui"
    },
    {
     "name": "Plaza",
     "colors": "Goldenrod",
     "category": "n\/a",
     "images": "http:\/\/dummyimage.com\/187x100.png\/ff4444\/ffffff",
     "brand": "Apollo Commercial Real Estate Finance",
     "stock": 21,
     "price": 37,
     "summary": "phasellus sit amet erat nulla tempus vivamus in felis eu sapien",
     "description": "fusce congue diam id ornare imperdiet sapien urna pretium nisl ut volutpat"
    },
    {
     "name": "Parkway",
     "colors": "Goldenrod",
     "category": "n\/a",
     "images": "http:\/\/dummyimage.com\/149x100.png\/ff4444\/ffffff",
     "brand": "Templeton Global Income Fund, Inc.",
     "stock": 22,
     "price": 73,
     "summary": "integer ac neque duis bibendum morbi non quam nec dui luctus rutrum nulla tellus in sagittis dui vel",
     "description": "pellentesque volutpat dui maecenas tristique est et tempus semper est quam pharetra magna ac consequat metus"
    },
    {
     "name": "Court",
     "colors": "Khaki",
     "category": "Consumer Durables",
     "images": "http:\/\/dummyimage.com\/232x100.png\/5fa2dd\/ffffff",
     "brand": "Central Garden &amp; Pet Company",
     "stock": 23,
     "price": 42,
     "summary": "rhoncus aliquet pulvinar sed nisl nunc rhoncus dui vel sem sed sagittis nam congue risus",
     "description": "adipiscing elit proin interdum mauris non ligula pellentesque ultrices phasellus id sapien in"
    },
    {
     "name": "Circle",
     "colors": "Fuscia",
     "category": "Capital Goods",
     "images": "http:\/\/dummyimage.com\/156x100.png\/dddddd\/000000",
     "brand": "China Ceramics Co., Ltd.",
     "stock": 24,
     "price": 15,
     "summary": "donec ut mauris eget massa tempor convallis nulla neque libero convallis eget eleifend luctus ultricies",
     "description": "congue etiam justo etiam pretium iaculis justo in hac habitasse platea dictumst etiam faucibus cursus urna"
    },
    {
     "name": "Parkway",
     "colors": "Mauv",
     "category": "Health Care",
     "images": "http:\/\/dummyimage.com\/192x100.png\/ff4444\/ffffff",
     "brand": "Oncobiologics, Inc.",
     "stock": 25,
     "price": 51,
     "summary": "quisque ut erat curabitur gravida nisi at nibh in hac habitasse platea dictumst aliquam augue quam sollicitudin vitae consectetuer eget",
     "description": "augue vestibulum ante ipsum primis in faucibus orci luctus et ultrices posuere cubilia curae donec"
    },
    {
     "name": "Crossing",
     "colors": "Aquamarine",
     "category": "Technology",
     "images": "http:\/\/dummyimage.com\/195x100.png\/cc0000\/ffffff",
     "brand": "NetApp, Inc.",
     "stock": 26,
     "price": 16,
     "summary": "diam erat fermentum justo nec condimentum neque sapien placerat ante nulla",
     "description": "ante nulla justo aliquam quis turpis eget elit sodales scelerisque mauris sit amet"
    },
    {
     "name": "Park",
     "colors": "Fuscia",
     "category": "Consumer Services",
     "images": "http:\/\/dummyimage.com\/150x100.png\/cc0000\/ffffff",
     "brand": "Reading International Inc",
     "stock": 27,
     "price": 42,
     "summary": "augue vestibulum ante ipsum primis in faucibus orci luctus et ultrices posuere",
     "description": "et commodo vulputate justo in blandit ultrices enim lorem ipsum dolor sit amet consectetuer adipiscing elit proin interdum"
    },
    {
     "name": "Place",
     "colors": "Teal",
     "category": "Capital Goods",
     "images": "http:\/\/dummyimage.com\/209x100.png\/dddddd\/000000",
     "brand": "Handy &amp; Harman Ltd.",
     "stock": 28,
     "price": 100,
     "summary": "morbi non lectus aliquam sit amet diam in magna bibendum imperdiet nullam orci pede",
     "description": "dapibus nulla suscipit ligula in lacus curabitur at ipsum ac"
    },
    {
     "name": "Circle",
     "colors": "Fuscia",
     "category": "n\/a",
     "images": "http:\/\/dummyimage.com\/117x100.png\/5fa2dd\/ffffff",
     "brand": "Blackrock MuniYield Quality Fund II, Inc.",
     "stock": 29,
     "price": 3,
     "summary": "ut odio cras mi pede malesuada in imperdiet et commodo vulputate justo",
     "description": "in tempus sit amet sem fusce consequat nulla nisl nunc nisl duis bibendum felis sed interdum venenatis turpis enim blandit"
    },
    {
     "name": "Drive",
     "colors": "Yellow",
     "category": "Finance",
     "images": "http:\/\/dummyimage.com\/132x100.png\/ff4444\/ffffff",
     "brand": "Heartland Financial USA, Inc.",
     "stock": 30,
     "price": 57,
     "summary": "amet lobortis sapien sapien non mi integer ac neque duis bibendum",
     "description": "quam suspendisse potenti nullam porttitor lacus at turpis donec posuere metus vitae ipsum aliquam non mauris morbi non"
    },
    {
     "name": "Plaza",
     "colors": "Mauv",
     "category": "Consumer Services",
     "images": "http:\/\/dummyimage.com\/155x100.png\/dddddd\/000000",
     "brand": "Camden Property Trust",
     "stock": 31,
     "price": 8,
     "summary": "potenti nullam porttitor lacus at turpis donec posuere metus vitae ipsum",
     "description": "primis in faucibus orci luctus et ultrices posuere cubilia curae nulla dapibus dolor vel est donec odio justo"
    },
    {
     "name": "Avenue",
     "colors": "Aquamarine",
     "category": "Transportation",
     "images": "http:\/\/dummyimage.com\/194x100.png\/cc0000\/ffffff",
     "brand": "China Southern Airlines Company Limited",
     "stock": 32,
     "price": 26,
     "summary": "consequat in consequat ut nulla sed accumsan felis ut at",
     "description": "id luctus nec molestie sed justo pellentesque viverra pede ac diam cras pellentesque"
    },
    {
     "name": "Circle",
     "colors": "Blue",
     "category": "Finance",
     "images": "http:\/\/dummyimage.com\/182x100.png\/5fa2dd\/ffffff",
     "brand": "Peoples Bancorp Inc.",
     "stock": 33,
     "price": 4,
     "summary": "nisi vulputate nonummy maecenas tincidunt lacus at velit vivamus vel nulla",
     "description": "primis in faucibus orci luctus et ultrices posuere cubilia curae nulla dapibus dolor vel"
    },
    {
     "name": "Court",
     "colors": "Khaki",
     "category": "Consumer Services",
     "images": "http:\/\/dummyimage.com\/197x100.png\/ff4444\/ffffff",
     "brand": "Allegion plc",
     "stock": 34,
     "price": 16,
     "summary": "dui maecenas tristique est et tempus semper est quam pharetra magna ac consequat metus",
     "description": "ornare imperdiet sapien urna pretium nisl ut volutpat sapien arcu sed augue aliquam erat"
    },
    {
     "name": "Drive",
     "colors": "Aquamarine",
     "category": "Consumer Services",
     "images": "http:\/\/dummyimage.com\/179x100.png\/ff4444\/ffffff",
     "brand": "Universal Technical Institute Inc",
     "stock": 35,
     "price": 39,
     "summary": "consequat morbi a ipsum integer a nibh in quis justo maecenas rhoncus aliquam lacus morbi",
     "description": "id ornare imperdiet sapien urna pretium nisl ut volutpat sapien arcu sed augue"
    },
    {
     "name": "Trail",
     "colors": "Pink",
     "category": "n\/a",
     "images": "http:\/\/dummyimage.com\/222x100.png\/cc0000\/ffffff",
     "brand": "NextEra Energy, Inc.",
     "stock": 36,
     "price": 99,
     "summary": "aenean fermentum donec ut mauris eget massa tempor convallis nulla neque libero convallis eget eleifend luctus ultricies eu",
     "description": "ligula in lacus curabitur at ipsum ac tellus semper interdum mauris ullamcorper purus sit"
    },
    {
     "name": "Center",
     "colors": "Orange",
     "category": "Consumer Services",
     "images": "http:\/\/dummyimage.com\/164x100.png\/cc0000\/ffffff",
     "brand": "Cogint, Inc.",
     "stock": 37,
     "price": 12,
     "summary": "leo rhoncus sed vestibulum sit amet cursus id turpis integer aliquet massa id lobortis convallis tortor risus dapibus augue",
     "description": "molestie sed justo pellentesque viverra pede ac diam cras pellentesque volutpat dui maecenas tristique est et"
    },
    {
     "name": "Crossing",
     "colors": "Red",
     "category": "Finance",
     "images": "http:\/\/dummyimage.com\/225x100.png\/dddddd\/000000",
     "brand": "Siebert Financial Corp.",
     "stock": 38,
     "price": 97,
     "summary": "sapien a libero nam dui proin leo odio porttitor id consequat in consequat ut nulla sed accumsan felis ut",
     "description": "vehicula consequat morbi a ipsum integer a nibh in quis"
    },
    {
     "name": "Street",
     "colors": "Puce",
     "category": "Public Utilities",
     "images": "http:\/\/dummyimage.com\/198x100.png\/dddddd\/000000",
     "brand": "National Grid Transco, PLC",
     "stock": 39,
     "price": 55,
     "summary": "donec semper sapien a libero nam dui proin leo odio",
     "description": "nec euismod scelerisque quam turpis adipiscing lorem vitae mattis nibh ligula nec sem duis aliquam convallis nunc proin at"
    },
    {
     "name": "Junction",
     "colors": "Red",
     "category": "n\/a",
     "images": "http:\/\/dummyimage.com\/250x100.png\/cc0000\/ffffff",
     "brand": "Newtek Business Services Corp.",
     "stock": 40,
     "price": 82,
     "summary": "nunc commodo placerat praesent blandit nam nulla integer pede justo lacinia eget tincidunt eget",
     "description": "ultrices mattis odio donec vitae nisi nam ultrices libero non mattis pulvinar"
    },
    {
     "name": "Point",
     "colors": "Puce",
     "category": "Health Care",
     "images": "http:\/\/dummyimage.com\/238x100.png\/cc0000\/ffffff",
     "brand": "BioLineRx Ltd.",
     "stock": 41,
     "price": 55,
     "summary": "vestibulum ac est lacinia nisi venenatis tristique fusce congue diam id ornare imperdiet sapien urna pretium nisl ut volutpat sapien",
     "description": "cubilia curae mauris viverra diam vitae quam suspendisse potenti nullam porttitor lacus at turpis donec"
    },
    {
     "name": "Pass",
     "colors": "Red",
     "category": "n\/a",
     "images": "http:\/\/dummyimage.com\/149x100.png\/ff4444\/ffffff",
     "brand": "CBL &amp; Associates Properties, Inc.",
     "stock": 42,
     "price": 99,
     "summary": "et ultrices posuere cubilia curae duis faucibus accumsan odio curabitur convallis duis consequat dui nec nisi volutpat eleifend donec",
     "description": "justo in blandit ultrices enim lorem ipsum dolor sit amet consectetuer"
    },
    {
     "name": "Hill",
     "colors": "Goldenrod",
     "category": "Health Care",
     "images": "http:\/\/dummyimage.com\/181x100.png\/dddddd\/000000",
     "brand": "Civitas Solutions, Inc.",
     "stock": 43,
     "price": 68,
     "summary": "phasellus id sapien in sapien iaculis congue vivamus metus arcu adipiscing molestie hendrerit at vulputate",
     "description": "amet sapien dignissim vestibulum vestibulum ante ipsum primis in faucibus orci luctus"
    },
    {
     "name": "Center",
     "colors": "Green",
     "category": "Health Care",
     "images": "http:\/\/dummyimage.com\/166x100.png\/ff4444\/ffffff",
     "brand": "Cerulean Pharma Inc.",
     "stock": 44,
     "price": 78,
     "summary": "mauris morbi non lectus aliquam sit amet diam in magna bibendum imperdiet nullam orci pede venenatis non sodales sed tincidunt",
     "description": "mauris lacinia sapien quis libero nullam sit amet turpis elementum ligula vehicula consequat morbi"
    },
    {
     "name": "Court",
     "colors": "Blue",
     "category": "Energy",
     "images": "http:\/\/dummyimage.com\/241x100.png\/cc0000\/ffffff",
     "brand": "Marathon Petroleum Corporation",
     "stock": 45,
     "price": 68,
     "summary": "quam a odio in hac habitasse platea dictumst maecenas ut massa quis augue luctus tincidunt nulla",
     "description": "ante vel ipsum praesent blandit lacinia erat vestibulum sed magna at nunc"
    },
    {
     "name": "Hill",
     "colors": "Green",
     "category": "Consumer Services",
     "images": "http:\/\/dummyimage.com\/161x100.png\/dddddd\/000000",
     "brand": "Aspen Aerogels, Inc.",
     "stock": 46,
     "price": 31,
     "summary": "et ultrices posuere cubilia curae mauris viverra diam vitae quam suspendisse potenti nullam porttitor lacus at turpis donec",
     "description": "curae donec pharetra magna vestibulum aliquet ultrices erat tortor sollicitudin mi sit"
    },
    {
     "name": "Plaza",
     "colors": "Blue",
     "category": "Capital Goods",
     "images": "http:\/\/dummyimage.com\/154x100.png\/dddddd\/000000",
     "brand": "Sun Hydraulics Corporation",
     "stock": 47,
     "price": 53,
     "summary": "tincidunt eu felis fusce posuere felis sed lacus morbi sem mauris laoreet ut rhoncus aliquet pulvinar",
     "description": "potenti cras in purus eu magna vulputate luctus cum sociis natoque penatibus et magnis dis"
    },
    {
     "name": "Road",
     "colors": "Orange",
     "category": "Energy",
     "images": "http:\/\/dummyimage.com\/240x100.png\/dddddd\/000000",
     "brand": "Suncor Energy  Inc.",
     "stock": 48,
     "price": 100,
     "summary": "ornare imperdiet sapien urna pretium nisl ut volutpat sapien arcu sed augue aliquam erat volutpat in",
     "description": "congue elementum in hac habitasse platea dictumst morbi vestibulum velit id pretium iaculis diam erat fermentum justo nec condimentum neque"
    },
    {
     "name": "Hill",
     "colors": "Maroon",
     "category": "Consumer Services",
     "images": "http:\/\/dummyimage.com\/218x100.png\/cc0000\/ffffff",
     "brand": "Xenia Hotels &amp; Resorts, Inc.",
     "stock": 49,
     "price": 36,
     "summary": "ut ultrices vel augue vestibulum ante ipsum primis in faucibus orci luctus et",
     "description": "justo nec condimentum neque sapien placerat ante nulla justo aliquam quis"
    },
    {
     "name": "Crossing",
     "colors": "Green",
     "category": "Health Care",
     "images": "http:\/\/dummyimage.com\/183x100.png\/5fa2dd\/ffffff",
     "brand": "Vical Incorporated",
     "stock": 50,
     "price": 47,
     "summary": "in felis eu sapien cursus vestibulum proin eu mi nulla ac enim in tempor",
     "description": "quam nec dui luctus rutrum nulla tellus in sagittis dui"
    },
    {
     "name": "Terrace",
     "colors": "Fuscia",
     "category": "Technology",
     "images": "http:\/\/dummyimage.com\/150x100.png\/5fa2dd\/ffffff",
     "brand": "HP Inc.",
     "stock": 51,
     "price": 56,
     "summary": "fermentum justo nec condimentum neque sapien placerat ante nulla justo aliquam quis turpis",
     "description": "vulputate vitae nisl aenean lectus pellentesque eget nunc donec quis orci eget orci vehicula condimentum curabitur in"
    },
    {
     "name": "Street",
     "colors": "Yellow",
     "category": "n\/a",
     "images": "http:\/\/dummyimage.com\/129x100.png\/ff4444\/ffffff",
     "brand": "Blackrock Municipal Income Quality Trust",
     "stock": 52,
     "price": 98,
     "summary": "at nunc commodo placerat praesent blandit nam nulla integer pede justo lacinia eget tincidunt eget",
     "description": "sapien sapien non mi integer ac neque duis bibendum morbi non quam nec dui"
    },
    {
     "name": "Place",
     "colors": "Aquamarine",
     "category": "Finance",
     "images": "http:\/\/dummyimage.com\/129x100.png\/5fa2dd\/ffffff",
     "brand": "Banco Santander Chile",
     "stock": 53,
     "price": 10,
     "summary": "nibh quisque id justo sit amet sapien dignissim vestibulum vestibulum ante ipsum primis in faucibus orci luctus et ultrices",
     "description": "vitae consectetuer eget rutrum at lorem integer tincidunt ante vel ipsum praesent blandit lacinia erat vestibulum sed"
    },
    {
     "name": "Crossing",
     "colors": "Aquamarine",
     "category": "Health Care",
     "images": "http:\/\/dummyimage.com\/195x100.png\/dddddd\/000000",
     "brand": "Neovasc Inc.",
     "stock": 54,
     "price": 44,
     "summary": "nibh in quis justo maecenas rhoncus aliquam lacus morbi quis tortor id nulla ultrices aliquet maecenas leo odio",
     "description": "magna vestibulum aliquet ultrices erat tortor sollicitudin mi sit amet lobortis sapien sapien non mi integer ac neque"
    },
    {
     "name": "Court",
     "colors": "Maroon",
     "category": "Finance",
     "images": "http:\/\/dummyimage.com\/129x100.png\/dddddd\/000000",
     "brand": "Lake Shore Bancorp, Inc.",
     "stock": 55,
     "price": 70,
     "summary": "elit ac nulla sed vel enim sit amet nunc viverra dapibus nulla suscipit ligula in lacus",
     "description": "in faucibus orci luctus et ultrices posuere cubilia curae duis faucibus accumsan odio curabitur"
    },
    {
     "name": "Road",
     "colors": "Red",
     "category": "Finance",
     "images": "http:\/\/dummyimage.com\/172x100.png\/5fa2dd\/ffffff",
     "brand": "First Defiance Financial Corp.",
     "stock": 56,
     "price": 18,
     "summary": "magnis dis parturient montes nascetur ridiculus mus etiam vel augue vestibulum rutrum rutrum neque aenean auctor gravida",
     "description": "sed justo pellentesque viverra pede ac diam cras pellentesque volutpat dui maecenas tristique est et"
    },
    {
     "name": "Avenue",
     "colors": "Pink",
     "category": "Consumer Services",
     "images": "http:\/\/dummyimage.com\/106x100.png\/dddddd\/000000",
     "brand": "Liberty Media Corporation",
     "stock": 57,
     "price": 72,
     "summary": "rhoncus aliquet pulvinar sed nisl nunc rhoncus dui vel sem sed sagittis nam congue risus semper porta volutpat",
     "description": "in purus eu magna vulputate luctus cum sociis natoque penatibus et magnis dis parturient montes"
    },
    {
     "name": "Place",
     "colors": "Khaki",
     "category": "Energy",
     "images": "http:\/\/dummyimage.com\/115x100.png\/ff4444\/ffffff",
     "brand": "Natural Resource Partners LP",
     "stock": 58,
     "price": 22,
     "summary": "risus semper porta volutpat quam pede lobortis ligula sit amet eleifend pede libero quis",
     "description": "felis sed interdum venenatis turpis enim blandit mi in porttitor pede justo eu massa donec dapibus"
    },
    {
     "name": "Lane",
     "colors": "Purple",
     "category": "Finance",
     "images": "http:\/\/dummyimage.com\/127x100.png\/ff4444\/ffffff",
     "brand": "Grupo Aval Acciones y Valores S.A.",
     "stock": 59,
     "price": 11,
     "summary": "ornare consequat lectus in est risus auctor sed tristique in tempus sit amet sem fusce",
     "description": "dui vel nisl duis ac nibh fusce lacus purus aliquet at feugiat non"
    },
    {
     "name": "Hill",
     "colors": "Khaki",
     "category": "Transportation",
     "images": "http:\/\/dummyimage.com\/154x100.png\/cc0000\/ffffff",
     "brand": "Star Bulk Carriers Corp.",
     "stock": 60,
     "price": 93,
     "summary": "phasellus id sapien in sapien iaculis congue vivamus metus arcu adipiscing molestie",
     "description": "facilisi cras non velit nec nisi vulputate nonummy maecenas tincidunt lacus at velit vivamus vel nulla eget eros elementum pellentesque"
    },
    {
     "name": "Point",
     "colors": "Khaki",
     "category": "Technology",
     "images": "http:\/\/dummyimage.com\/166x100.png\/cc0000\/ffffff",
     "brand": "ChipMOS TECHNOLOGIES INC.",
     "stock": 61,
     "price": 1,
     "summary": "quisque arcu libero rutrum ac lobortis vel dapibus at diam nam tristique tortor eu pede",
     "description": "rhoncus aliquam lacus morbi quis tortor id nulla ultrices aliquet maecenas leo odio condimentum"
    },
    {
     "name": "Street",
     "colors": "Aquamarine",
     "category": "Public Utilities",
     "images": "http:\/\/dummyimage.com\/215x100.png\/cc0000\/ffffff",
     "brand": "Mobile TeleSystems OJSC",
     "stock": 62,
     "price": 79,
     "summary": "fringilla rhoncus mauris enim leo rhoncus sed vestibulum sit amet cursus id turpis integer aliquet massa id",
     "description": "habitasse platea dictumst aliquam augue quam sollicitudin vitae consectetuer eget rutrum at lorem"
    },
    {
     "name": "Junction",
     "colors": "Mauv",
     "category": "Health Care",
     "images": "http:\/\/dummyimage.com\/183x100.png\/dddddd\/000000",
     "brand": "Advaxis, Inc.",
     "stock": 63,
     "price": 42,
     "summary": "justo in blandit ultrices enim lorem ipsum dolor sit amet consectetuer adipiscing elit proin interdum",
     "description": "ultrices erat tortor sollicitudin mi sit amet lobortis sapien sapien non"
    },
    {
     "name": "Way",
     "colors": "Crimson",
     "category": "Finance",
     "images": "http:\/\/dummyimage.com\/104x100.png\/cc0000\/ffffff",
     "brand": "Government Properties Income Trust",
     "stock": 64,
     "price": 33,
     "summary": "eu massa donec dapibus duis at velit eu est congue",
     "description": "sollicitudin mi sit amet lobortis sapien sapien non mi integer ac neque duis bibendum morbi"
    },
    {
     "name": "Terrace",
     "colors": "Teal",
     "category": "Finance",
     "images": "http:\/\/dummyimage.com\/179x100.png\/cc0000\/ffffff",
     "brand": "Plumas Bancorp",
     "stock": 65,
     "price": 98,
     "summary": "ante vivamus tortor duis mattis egestas metus aenean fermentum donec ut",
     "description": "ipsum praesent blandit lacinia erat vestibulum sed magna at nunc commodo placerat praesent"
    },
    {
     "name": "Court",
     "colors": "Blue",
     "category": "Finance",
     "images": "http:\/\/dummyimage.com\/174x100.png\/cc0000\/ffffff",
     "brand": "Virtus Investment Partners, Inc.",
     "stock": 66,
     "price": 64,
     "summary": "vel pede morbi porttitor lorem id ligula suspendisse ornare consequat",
     "description": "ullamcorper augue a suscipit nulla elit ac nulla sed vel enim sit amet nunc viverra dapibus nulla suscipit ligula in"
    },
    {
     "name": "Place",
     "colors": "Pink",
     "category": "Consumer Services",
     "images": "http:\/\/dummyimage.com\/231x100.png\/ff4444\/ffffff",
     "brand": "Grand Canyon Education, Inc.",
     "stock": 67,
     "price": 96,
     "summary": "nisl nunc nisl duis bibendum felis sed interdum venenatis turpis enim blandit mi in porttitor pede justo eu massa donec",
     "description": "eget vulputate ut ultrices vel augue vestibulum ante ipsum primis in faucibus orci luctus et"
    },
    {
     "name": "Circle",
     "colors": "Orange",
     "category": "Consumer Services",
     "images": "http:\/\/dummyimage.com\/225x100.png\/5fa2dd\/ffffff",
     "brand": "Salem Media Group, Inc.",
     "stock": 68,
     "price": 3,
     "summary": "nec euismod scelerisque quam turpis adipiscing lorem vitae mattis nibh ligula nec sem",
     "description": "vivamus in felis eu sapien cursus vestibulum proin eu mi nulla ac enim"
    },
    {
     "name": "Road",
     "colors": "Yellow",
     "category": "Health Care",
     "images": "http:\/\/dummyimage.com\/236x100.png\/cc0000\/ffffff",
     "brand": "Aetna Inc.",
     "stock": 69,
     "price": 10,
     "summary": "platea dictumst aliquam augue quam sollicitudin vitae consectetuer eget rutrum at lorem integer tincidunt ante vel ipsum praesent blandit",
     "description": "ligula nec sem duis aliquam convallis nunc proin at turpis a pede posuere nonummy integer non velit donec diam"
    },
    {
     "name": "Terrace",
     "colors": "Teal",
     "category": "Finance",
     "images": "http:\/\/dummyimage.com\/198x100.png\/5fa2dd\/ffffff",
     "brand": "Yintech Investment Holdings Limited",
     "stock": 70,
     "price": 78,
     "summary": "tempus vivamus in felis eu sapien cursus vestibulum proin eu mi nulla ac enim in tempor turpis nec euismod scelerisque",
     "description": "proin leo odio porttitor id consequat in consequat ut nulla sed accumsan"
    },
    {
     "name": "Crossing",
     "colors": "Indigo",
     "category": "Finance",
     "images": "http:\/\/dummyimage.com\/154x100.png\/5fa2dd\/ffffff",
     "brand": "Marlin Business Services Corp.",
     "stock": 71,
     "price": 47,
     "summary": "nec dui luctus rutrum nulla tellus in sagittis dui vel nisl duis ac nibh",
     "description": "quam fringilla rhoncus mauris enim leo rhoncus sed vestibulum sit amet cursus id turpis"
    },
    {
     "name": "Point",
     "colors": "Red",
     "category": "Health Care",
     "images": "http:\/\/dummyimage.com\/113x100.png\/5fa2dd\/ffffff",
     "brand": "TRACON Pharmaceuticals, Inc.",
     "stock": 72,
     "price": 45,
     "summary": "eros suspendisse accumsan tortor quis turpis sed ante vivamus tortor duis mattis egestas metus aenean",
     "description": "integer pede justo lacinia eget tincidunt eget tempus vel pede morbi porttitor lorem id ligula suspendisse"
    },
    {
     "name": "Park",
     "colors": "Red",
     "category": "Finance",
     "images": "http:\/\/dummyimage.com\/241x100.png\/cc0000\/ffffff",
     "brand": "Baldwin &amp; Lyons, Inc.",
     "stock": 73,
     "price": 58,
     "summary": "in hac habitasse platea dictumst maecenas ut massa quis augue luctus tincidunt nulla",
     "description": "dui luctus rutrum nulla tellus in sagittis dui vel nisl duis ac nibh fusce lacus purus"
    },
    {
     "name": "Center",
     "colors": "Maroon",
     "category": "Miscellaneous",
     "images": "http:\/\/dummyimage.com\/219x100.png\/dddddd\/000000",
     "brand": "Shutterfly, Inc.",
     "stock": 74,
     "price": 48,
     "summary": "a nibh in quis justo maecenas rhoncus aliquam lacus morbi quis tortor id nulla ultrices aliquet maecenas leo odio condimentum",
     "description": "praesent blandit lacinia erat vestibulum sed magna at nunc commodo placerat"
    },
    {
     "name": "Crossing",
     "colors": "Purple",
     "category": "n\/a",
     "images": "http:\/\/dummyimage.com\/100x100.png\/ff4444\/ffffff",
     "brand": "NCS Multistage Holdings, Inc.",
     "stock": 75,
     "price": 1,
     "summary": "tellus in sagittis dui vel nisl duis ac nibh fusce lacus purus aliquet at feugiat",
     "description": "eros vestibulum ac est lacinia nisi venenatis tristique fusce congue diam id ornare imperdiet sapien urna"
    },
    {
     "name": "Hill",
     "colors": "Red",
     "category": "Finance",
     "images": "http:\/\/dummyimage.com\/146x100.png\/5fa2dd\/ffffff",
     "brand": "Sussex Bancorp",
     "stock": 76,
     "price": 28,
     "summary": "parturient montes nascetur ridiculus mus etiam vel augue vestibulum rutrum rutrum neque aenean auctor gravida sem praesent",
     "description": "venenatis turpis enim blandit mi in porttitor pede justo eu massa donec dapibus duis"
    },
    {
     "name": "Drive",
     "colors": "Khaki",
     "category": "Technology",
     "images": "http:\/\/dummyimage.com\/165x100.png\/5fa2dd\/ffffff",
     "brand": "Motorola Solutions, Inc.",
     "stock": 77,
     "price": 65,
     "summary": "morbi sem mauris laoreet ut rhoncus aliquet pulvinar sed nisl",
     "description": "sed tristique in tempus sit amet sem fusce consequat nulla nisl nunc nisl duis bibendum"
    },
    {
     "name": "Street",
     "colors": "Crimson",
     "category": "n\/a",
     "images": "http:\/\/dummyimage.com\/140x100.png\/5fa2dd\/ffffff",
     "brand": "Gabelli Global Small and Mid Cap Value Trust (The)",
     "stock": 78,
     "price": 96,
     "summary": "faucibus orci luctus et ultrices posuere cubilia curae mauris viverra diam vitae quam suspendisse potenti nullam porttitor",
     "description": "duis mattis egestas metus aenean fermentum donec ut mauris eget massa"
    },
    {
     "name": "Hill",
     "colors": "Teal",
     "category": "Technology",
     "images": "http:\/\/dummyimage.com\/248x100.png\/dddddd\/000000",
     "brand": "Concurrent Computer Corporation",
     "stock": 79,
     "price": 16,
     "summary": "at nulla suspendisse potenti cras in purus eu magna vulputate luctus cum sociis natoque penatibus et magnis dis parturient montes",
     "description": "quisque erat eros viverra eget congue eget semper rutrum nulla nunc purus"
    },
    {
     "name": "Point",
     "colors": "Crimson",
     "category": "Basic Industries",
     "images": "http:\/\/dummyimage.com\/207x100.png\/cc0000\/ffffff",
     "brand": "Kinross Gold Corporation",
     "stock": 80,
     "price": 92,
     "summary": "aenean auctor gravida sem praesent id massa id nisl venenatis lacinia aenean sit amet justo morbi",
     "description": "pretium iaculis justo in hac habitasse platea dictumst etiam faucibus cursus urna ut tellus nulla ut erat id"
    },
    {
     "name": "Hill",
     "colors": "Fuscia",
     "category": "Health Care",
     "images": "http:\/\/dummyimage.com\/211x100.png\/ff4444\/ffffff",
     "brand": "Synergy Pharmaceuticals, Inc.",
     "stock": 81,
     "price": 47,
     "summary": "a suscipit nulla elit ac nulla sed vel enim sit amet",
     "description": "imperdiet et commodo vulputate justo in blandit ultrices enim lorem ipsum dolor sit amet"
    },
    {
     "name": "Circle",
     "colors": "Turquoise",
     "category": "n\/a",
     "images": "http:\/\/dummyimage.com\/103x100.png\/dddddd\/000000",
     "brand": "Invesco Trust for Investment Grade Municipals",
     "stock": 82,
     "price": 33,
     "summary": "mauris ullamcorper purus sit amet nulla quisque arcu libero rutrum ac lobortis vel dapibus",
     "description": "aliquam lacus morbi quis tortor id nulla ultrices aliquet maecenas leo odio condimentum id luctus nec molestie sed justo"
    },
    {
     "name": "Center",
     "colors": "Turquoise",
     "category": "Technology",
     "images": "http:\/\/dummyimage.com\/130x100.png\/ff4444\/ffffff",
     "brand": "SS&amp;C Technologies Holdings, Inc.",
     "stock": 83,
     "price": 8,
     "summary": "euismod scelerisque quam turpis adipiscing lorem vitae mattis nibh ligula nec",
     "description": "semper porta volutpat quam pede lobortis ligula sit amet eleifend pede libero quis orci nullam molestie nibh in lectus pellentesque"
    },
    {
     "name": "Drive",
     "colors": "Orange",
     "category": "Finance",
     "images": "http:\/\/dummyimage.com\/122x100.png\/ff4444\/ffffff",
     "brand": "Saban Capital Acquisition Corp.",
     "stock": 84,
     "price": 84,
     "summary": "justo eu massa donec dapibus duis at velit eu est congue elementum in hac habitasse platea dictumst morbi",
     "description": "semper porta volutpat quam pede lobortis ligula sit amet eleifend pede libero quis orci"
    },
    {
     "name": "Crossing",
     "colors": "Goldenrod",
     "category": "Consumer Non-Durables",
     "images": "http:\/\/dummyimage.com\/147x100.png\/dddddd\/000000",
     "brand": "Deckers Outdoor Corporation",
     "stock": 85,
     "price": 97,
     "summary": "id nulla ultrices aliquet maecenas leo odio condimentum id luctus nec molestie sed justo pellentesque viverra",
     "description": "neque vestibulum eget vulputate ut ultrices vel augue vestibulum ante ipsum primis in faucibus orci luctus et"
    },
    {
     "name": "Lane",
     "colors": "Turquoise",
     "category": "Finance",
     "images": "http:\/\/dummyimage.com\/101x100.png\/ff4444\/ffffff",
     "brand": "National Western Life Group, Inc.",
     "stock": 86,
     "price": 72,
     "summary": "lorem id ligula suspendisse ornare consequat lectus in est risus auctor sed",
     "description": "at dolor quis odio consequat varius integer ac leo pellentesque ultrices mattis odio donec vitae"
    },
    {
     "name": "Hill",
     "colors": "Pink",
     "category": "Technology",
     "images": "http:\/\/dummyimage.com\/116x100.png\/dddddd\/000000",
     "brand": "QUALCOMM Incorporated",
     "stock": 87,
     "price": 5,
     "summary": "ut at dolor quis odio consequat varius integer ac leo pellentesque ultrices mattis odio donec vitae nisi",
     "description": "ipsum primis in faucibus orci luctus et ultrices posuere cubilia"
    },
    {
     "name": "Court",
     "colors": "Indigo",
     "category": "n\/a",
     "images": "http:\/\/dummyimage.com\/234x100.png\/cc0000\/ffffff",
     "brand": "Medley Capital Corporation",
     "stock": 88,
     "price": 59,
     "summary": "nisi vulputate nonummy maecenas tincidunt lacus at velit vivamus vel nulla",
     "description": "velit eu est congue elementum in hac habitasse platea dictumst morbi vestibulum velit id"
    },
    {
     "name": "Center",
     "colors": "Green",
     "category": "Capital Goods",
     "images": "http:\/\/dummyimage.com\/147x100.png\/ff4444\/ffffff",
     "brand": "Greenbrier Companies, Inc. (The)",
     "stock": 89,
     "price": 87,
     "summary": "dignissim vestibulum vestibulum ante ipsum primis in faucibus orci luctus et",
     "description": "eros suspendisse accumsan tortor quis turpis sed ante vivamus tortor duis mattis egestas"
    },
    {
     "name": "Avenue",
     "colors": "Turquoise",
     "category": "Energy",
     "images": "http:\/\/dummyimage.com\/212x100.png\/dddddd\/000000",
     "brand": "Eclipse Resources Corporation",
     "stock": 90,
     "price": 80,
     "summary": "fusce congue diam id ornare imperdiet sapien urna pretium nisl",
     "description": "ut odio cras mi pede malesuada in imperdiet et commodo vulputate justo in blandit ultrices enim lorem ipsum dolor"
    },
    {
     "name": "Center",
     "colors": "Violet",
     "category": "Technology",
     "images": "http:\/\/dummyimage.com\/158x100.png\/cc0000\/ffffff",
     "brand": "Proofpoint, Inc.",
     "stock": 91,
     "price": 30,
     "summary": "ut blandit non interdum in ante vestibulum ante ipsum primis in faucibus orci luctus",
     "description": "justo eu massa donec dapibus duis at velit eu est congue elementum in hac habitasse"
    },
    {
     "name": "Hill",
     "colors": "Yellow",
     "category": "Miscellaneous",
     "images": "http:\/\/dummyimage.com\/116x100.png\/5fa2dd\/ffffff",
     "brand": "Fidelity National Information Services, Inc.",
     "stock": 92,
     "price": 23,
     "summary": "luctus cum sociis natoque penatibus et magnis dis parturient montes nascetur ridiculus mus vivamus vestibulum sagittis",
     "description": "nunc rhoncus dui vel sem sed sagittis nam congue risus semper porta volutpat quam pede lobortis ligula sit amet"
    },
    {
     "name": "Park",
     "colors": "Violet",
     "category": "Finance",
     "images": "http:\/\/dummyimage.com\/163x100.png\/cc0000\/ffffff",
     "brand": "iPath US Treasury 2-year Bull ETN",
     "stock": 93,
     "price": 96,
     "summary": "nulla ultrices aliquet maecenas leo odio condimentum id luctus nec molestie sed justo pellentesque viverra pede ac diam cras",
     "description": "faucibus cursus urna ut tellus nulla ut erat id mauris vulputate elementum"
    },
    {
     "name": "Road",
     "colors": "Fuscia",
     "category": "Basic Industries",
     "images": "http:\/\/dummyimage.com\/127x100.png\/ff4444\/ffffff",
     "brand": "OCI Partners LP",
     "stock": 94,
     "price": 86,
     "summary": "sapien urna pretium nisl ut volutpat sapien arcu sed augue aliquam erat volutpat in",
     "description": "sed sagittis nam congue risus semper porta volutpat quam pede lobortis ligula sit amet eleifend pede libero quis orci"
    },
    {
     "name": "Parkway",
     "colors": "Khaki",
     "category": "Finance",
     "images": "http:\/\/dummyimage.com\/143x100.png\/dddddd\/000000",
     "brand": "People's Utah Bancorp",
     "stock": 95,
     "price": 18,
     "summary": "urna pretium nisl ut volutpat sapien arcu sed augue aliquam erat volutpat",
     "description": "enim sit amet nunc viverra dapibus nulla suscipit ligula in lacus curabitur at ipsum ac tellus semper"
    },
    {
     "name": "Park",
     "colors": "Mauv",
     "category": "Technology",
     "images": "http:\/\/dummyimage.com\/188x100.png\/dddddd\/000000",
     "brand": "Marvell Technology Group Ltd.",
     "stock": 96,
     "price": 18,
     "summary": "blandit mi in porttitor pede justo eu massa donec dapibus duis at velit",
     "description": "arcu libero rutrum ac lobortis vel dapibus at diam nam tristique"
    },
    {
     "name": "Place",
     "colors": "Turquoise",
     "category": "Consumer Services",
     "images": "http:\/\/dummyimage.com\/231x100.png\/5fa2dd\/ffffff",
     "brand": "Red Lion Hotels Corporation",
     "stock": 97,
     "price": 18,
     "summary": "luctus et ultrices posuere cubilia curae nulla dapibus dolor vel est donec odio justo sollicitudin ut suscipit a feugiat",
     "description": "sollicitudin mi sit amet lobortis sapien sapien non mi integer"
    },
    {
     "name": "Pass",
     "colors": "Purple",
     "category": "n\/a",
     "images": "http:\/\/dummyimage.com\/199x100.png\/5fa2dd\/ffffff",
     "brand": "Mota Group, Inc.",
     "stock": 98,
     "price": 20,
     "summary": "consequat varius integer ac leo pellentesque ultrices mattis odio donec vitae nisi nam ultrices libero non mattis pulvinar",
     "description": "consequat dui nec nisi volutpat eleifend donec ut dolor morbi vel lectus in quam fringilla rhoncus"
    },
    {
     "name": "Crossing",
     "colors": "Puce",
     "category": "Consumer Services",
     "images": "http:\/\/dummyimage.com\/146x100.png\/ff4444\/ffffff",
     "brand": "Lightbridge Corporation",
     "stock": 99,
     "price": 48,
     "summary": "ut odio cras mi pede malesuada in imperdiet et commodo vulputate justo in",
     "description": "quam fringilla rhoncus mauris enim leo rhoncus sed vestibulum sit amet cursus id"
    },
    {
     "name": "Junction",
     "colors": "Goldenrod",
     "category": "Finance",
     "images": "http:\/\/dummyimage.com\/191x100.png\/cc0000\/ffffff",
     "brand": "Civista Bancshares, Inc. ",
     "stock": 100,
     "price": 100,
     "summary": "sit amet sem fusce consequat nulla nisl nunc nisl duis bibendum felis sed interdum venenatis turpis enim blandit mi in",
     "description": "est congue elementum in hac habitasse platea dictumst morbi vestibulum"
    }
   ]

export default data